### ISSUE TITLE
error

### ISSUE THREAD

**Issue by OlevO1** [sujang958/N-word-counter#5]
Hi error 
![image](https://github.com/sujang958/N-word-counter/assets/95526844/c2efcf16-a028-4476-8daf-86f18e996693)
please help me 
![image](https://github.com/sujang958/N-word-counter/assets/95526844/12ed6dcb-522e-4d7a-a025-668282a7a50e)
![image](https://github.com/sujang958/N-word-counter/assets/95526844/4d3c57a7-a1bf-4cf6-9139-58696f53ac9e)

**Comment by OlevO1** [comment]
the bot does not respond to n-word

**Comment by sujang958** [comment]
you should use PostgreSQL, not MySQL
